const picUrls = {};
picUrls.lite = {
    three: [
        [
            picsUrls.lite[0],
            picsUrls.lite[1],
            picsUrls.lite[2]
        ],
        [
            picsUrls.lite[5],
            picsUrls.lite[6],
            picsUrls.lite[7]
        ],
        [
            picsUrls.lite[10],
            picsUrls.lite[11],
            picsUrls.lite[12]
        ],
        [
            picsUrls.lite[15],
            picsUrls.lite[16],
            picsUrls.lite[17]
        ],
        [
            picsUrls.lite[20],
            picsUrls.lite[21],
            picsUrls.lite[22]
        ],
        [
            picsUrls.lite[25],
            picsUrls.lite[26],
            picsUrls.lite[27]
        ],
        [
            picsUrls.lite[30],
            picsUrls.lite[31],
            picsUrls.lite[32]
        ],
    ],
    five: [
        [
            picsUrls.lite[0],
            picsUrls.lite[1],
            picsUrls.lite[2],
            picsUrls.lite[3],
            picsUrls.lite[4]
        ],
        [
            picsUrls.lite[5],
            picsUrls.lite[6],
            picsUrls.lite[7],
            picsUrls.lite[8],
            picsUrls.lite[9]
        ],
        [
            picsUrls.lite[10],
            picsUrls.lite[11],
            picsUrls.lite[12],
            picsUrls.lite[13],
            picsUrls.lite[14]
        ],
        [
            picsUrls.lite[15],
            picsUrls.lite[16],
            picsUrls.lite[17],
            picsUrls.lite[18],
            picsUrls.lite[19]
        ],
        [
            picsUrls.lite[20],
            picsUrls.lite[21],
            picsUrls.lite[22],
            picsUrls.lite[23],
            picsUrls.lite[24]
        ],
        [
            picsUrls.lite[25],
            picsUrls.lite[26],
            picsUrls.lite[27],
            picsUrls.lite[28],
            picsUrls.lite[29]
        ],
        [
            picsUrls.lite[30],
            picsUrls.lite[31],
            picsUrls.lite[32],
            picsUrls.lite[33],
            picsUrls.lite[34]
        ],
    ]
}