const picUrls = {};
picUrls.home = {
    three: [
        [
            picsUrls.home[0],
            picsUrls.home[1],
            picsUrls.home[2]
        ],
        [
            picsUrls.home[3],
            picsUrls.home[4],
            picsUrls.home[5]
        ],
        [
            picsUrls.home[6],
            picsUrls.home[7],
            picsUrls.home[8]
        ],
        [
            picsUrls.home[9],
            picsUrls.home[10],
            picsUrls.home[11]
        ],
        [
            picsUrls.home[12],
            picsUrls.home[13],
            picsUrls.home[14]
        ],
        [
            picsUrls.home[15],
            picsUrls.home[16],
            picsUrls.home[17]
        ],
        [
            picsUrls.home[18],
            picsUrls.home[19],
            picsUrls.home[20]
        ],
    ],
    four: [
        [
            picsUrls.home[0],
            picsUrls.home[1],
            picsUrls.home[2],
            picsUrls.home[21]
        ],
        [
            picsUrls.home[3],
            picsUrls.home[4],
            picsUrls.home[5],
            picsUrls.home[22]
        ],
        [
            picsUrls.home[6],
            picsUrls.home[7],
            picsUrls.home[8],
            picsUrls.home[23]
        ],
        [
            picsUrls.home[9],
            picsUrls.home[10],
            picsUrls.home[11],
            picsUrls.home[24]
        ],
        [
            picsUrls.home[12],
            picsUrls.home[13],
            picsUrls.home[14],
            picsUrls.home[25]
        ],
        [
            picsUrls.home[15],
            picsUrls.home[16],
            picsUrls.home[17],
            picsUrls.home[26]
        ],
        [
            picsUrls.home[18],
            picsUrls.home[19],
            picsUrls.home[20],
            picsUrls.home[27]
        ],
    ],
    five: [
        [
            picsUrls.home[0],
            picsUrls.home[1],
            picsUrls.home[2],
            picsUrls.home[28],
            picsUrls.home[29]
        ],
        [
            picsUrls.home[3],
            picsUrls.home[4],
            picsUrls.home[5],
            picsUrls.home[30],
            picsUrls.home[31]
        ],
        [
            picsUrls.home[6],
            picsUrls.home[7],
            picsUrls.home[8],
            picsUrls.home[32],
            picsUrls.home[33]
        ],
        [
            picsUrls.home[9],
            picsUrls.home[10],
            picsUrls.home[11],
            picsUrls.home[34],
            picsUrls.home[35]
        ],
        [
            picsUrls.home[12],
            picsUrls.home[13],
            picsUrls.home[14],
            picsUrls.home[36],
            picsUrls.home[37]
        ],
        [
            picsUrls.home[15],
            picsUrls.home[16],
            picsUrls.home[17],
            picsUrls.home[38],
            picsUrls.home[39]
        ],
        [
            picsUrls.home[18],
            picsUrls.home[19],
            picsUrls.home[20],
            picsUrls.home[40],
            picsUrls.home[41]
        ],
    ],
    six: [
        [
            picsUrls.home[0],
            picsUrls.home[1],
            picsUrls.home[2],
            picsUrls.home[28],
            picsUrls.home[29],
            picsUrls.home[21]
        ],
        [
            picsUrls.home[3],
            picsUrls.home[4],
            picsUrls.home[5],
            picsUrls.home[30],
            picsUrls.home[31],
            picsUrls.home[22]
        ],
        [
            picsUrls.home[6],
            picsUrls.home[7],
            picsUrls.home[8],
            picsUrls.home[32],
            picsUrls.home[33],
            picsUrls.home[23]
        ],
        [
            picsUrls.home[9],
            picsUrls.home[10],
            picsUrls.home[11],
            picsUrls.home[34],
            picsUrls.home[35],
            picsUrls.home[24]
        ],
        [
            picsUrls.home[12],
            picsUrls.home[13],
            picsUrls.home[14],
            picsUrls.home[36],
            picsUrls.home[37],
            picsUrls.home[25]
        ],
        [
            picsUrls.home[15],
            picsUrls.home[16],
            picsUrls.home[17],
            picsUrls.home[38],
            picsUrls.home[39],
            picsUrls.home[26]
        ],
        [
            picsUrls.home[18],
            picsUrls.home[19],
            picsUrls.home[20],
            picsUrls.home[40],
            picsUrls.home[41],
            picsUrls.home[27]
        ],
    ]
}