const picUrls = {};
picUrls.avan = {
    three: [
        [
            picsUrls.avan[0],
            picsUrls.avan[1],
            picsUrls.avan[2]
        ],
        [
            picsUrls.avan[3],
            picsUrls.avan[4],
            picsUrls.avan[5]
        ],
        [
            picsUrls.avan[6],
            picsUrls.avan[7],
            picsUrls.avan[8]
        ],
        [
            picsUrls.avan[9],
            picsUrls.avan[10],
            picsUrls.avan[11]
        ],
        [
            picsUrls.avan[12],
            picsUrls.avan[13],
            picsUrls.avan[14]
        ],
        [
            picsUrls.avan[15],
            picsUrls.avan[16],
            picsUrls.avan[17]
        ],
        [
            picsUrls.avan[18],
            picsUrls.avan[19],
            picsUrls.avan[20]
        ],
    ],
    four: [
        [
            picsUrls.avan[0],
            picsUrls.avan[1],
            picsUrls.avan[2],
            picsUrls.avan[21]
        ],
        [
            picsUrls.avan[3],
            picsUrls.avan[4],
            picsUrls.avan[5],
            picsUrls.avan[22]
        ],
        [
            picsUrls.avan[6],
            picsUrls.avan[7],
            picsUrls.avan[8],
            picsUrls.avan[23]
        ],
        [
            picsUrls.avan[9],
            picsUrls.avan[10],
            picsUrls.avan[11],
            picsUrls.avan[24]
        ],
        [
            picsUrls.avan[12],
            picsUrls.avan[13],
            picsUrls.avan[14],
            picsUrls.avan[25]
        ],
        [
            picsUrls.avan[15],
            picsUrls.avan[16],
            picsUrls.avan[17],
            picsUrls.avan[26]
        ],
        [
            picsUrls.avan[18],
            picsUrls.avan[19],
            picsUrls.avan[20],
            picsUrls.avan[27]
        ],
    ],
    five: [
        [
            picsUrls.avan[0],
            picsUrls.avan[1],
            picsUrls.avan[2],
            picsUrls.avan[28],
            picsUrls.avan[29]
        ],
        [
            picsUrls.avan[3],
            picsUrls.avan[4],
            picsUrls.avan[5],
            picsUrls.avan[30],
            picsUrls.avan[31]
        ],
        [
            picsUrls.avan[6],
            picsUrls.avan[7],
            picsUrls.avan[8],
            picsUrls.avan[32],
            picsUrls.avan[33]
        ],
        [
            picsUrls.avan[9],
            picsUrls.avan[10],
            picsUrls.avan[11],
            picsUrls.avan[34],
            picsUrls.avan[35]
        ],
        [
            picsUrls.avan[12],
            picsUrls.avan[13],
            picsUrls.avan[14],
            picsUrls.avan[36],
            picsUrls.avan[37]
        ],
        [
            picsUrls.avan[15],
            picsUrls.avan[16],
            picsUrls.avan[17],
            picsUrls.avan[38],
            picsUrls.avan[39]
        ],
        [
            picsUrls.avan[18],
            picsUrls.avan[19],
            picsUrls.avan[20],
            picsUrls.avan[40],
            picsUrls.avan[41]
        ],
    ],
    six: [
        [
            picsUrls.avan[0],
            picsUrls.avan[1],
            picsUrls.avan[2],
            picsUrls.avan[28],
            picsUrls.avan[29],
            picsUrls.avan[21]
        ],
        [
            picsUrls.avan[3],
            picsUrls.avan[4],
            picsUrls.avan[5],
            picsUrls.avan[30],
            picsUrls.avan[31],
            picsUrls.avan[22]
        ],
        [
            picsUrls.avan[6],
            picsUrls.avan[7],
            picsUrls.avan[8],
            picsUrls.avan[32],
            picsUrls.avan[33],
            picsUrls.avan[23]
        ],
        [
            picsUrls.avan[9],
            picsUrls.avan[10],
            picsUrls.avan[11],
            picsUrls.avan[34],
            picsUrls.avan[35],
            picsUrls.avan[24]
        ],
        [
            picsUrls.avan[12],
            picsUrls.avan[13],
            picsUrls.avan[14],
            picsUrls.avan[36],
            picsUrls.avan[37],
            picsUrls.avan[25]
        ],
        [
            picsUrls.avan[15],
            picsUrls.avan[16],
            picsUrls.avan[17],
            picsUrls.avan[38],
            picsUrls.avan[39],
            picsUrls.avan[26]
        ],
        [
            picsUrls.avan[18],
            picsUrls.avan[19],
            picsUrls.avan[20],
            picsUrls.avan[40],
            picsUrls.avan[41],
            picsUrls.avan[27]
        ],
    ]
}